#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions
rm -r log.chtMultiRegionFoam

runApplication $(getApplication)


#------------------------------------------------------------------------------
