#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

./Allclean
ideasUnvToFoam cht_onePipeHeatExchg.unv
#polyDualMesh 75 -overwrite 
transformPoints -scale 0.001
restore0Dir

splitMeshRegions -cellZones -overwrite


# Remove fluid fields from solid regions (important for post-processing)
for region in $(foamListRegions solid)
do
    rm -f 0/$region/{nut,alphat,epsilon,k,U,p_rgh,omega}
    rm -f processor*/0/$region/{nut,alphat,epsilon,k,U,p_rgh,omega}
done

for region in $(foamListRegions)
do
    runApplication -s $region changeDictionary -region $region
done

touch cht_onePipeHeatExchanger.foam

#------------------------------------------------------------------------------
