#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

./Allrun-serial-pre

runApplication decomposePar -allRegions

#-- Run in parallel
runParallel $(getApplication)

# Reconstruct
runApplication reconstructPar -allRegions


echo
echo "Use paraFoam -touch-all to create files for paraview post-processing"
echo

#------------------------------------------------------------------------------
