#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

./Allclean
ideasUnvToFoam cht_onePipeHeatExchg.unv
#polyDualMesh 75 -overwrite 
transformPoints -scale 0.001


splitMeshRegions -cellZones -overwrite

touch cht_onePipeHeatExchanger.foam

#------------------------------------------------------------------------------
